### ISSUE TITLE
Getting a 500 status when requesting badge

### ISSUE THREAD

**Issue by ceharris** [jirutka/maven-badges#4]
Requesting a badge using 

`https://maven-badges.herokuapp.com/maven-central/org.soulwing/crypt4j/badge.svg`

**Comment by melezov** [comment]
Same thing here: [![Maven Central](https://maven-badges.herokuapp.com/maven-central/io.jvm.uuid/scala-uuid_2.11/badge.svg)](https://maven-badges.herokuapp.com/maven-central/io.jvm.uuid/scala-uuid_2.11)

**Comment by cogmission** [comment]
I'm seeing problems with this too!

**Comment by idelvall** [comment]
+1

**Comment by jirutka** [comment]
I’m getting SSL error on Heroku:

```
2015-10-20T16:59:52.254093+00:00 heroku[router]: at=info method=GET path="/maven-central/org.annolab.tt4j/org.annolab.tt4j/badge.svg" host=maven-badges.herokuapp.com request_id=3c865520-9850-4cbb-98fa-fe7ac8a06968 fwd="54.144.81.236" dyno=web.1 connect=0ms service=94ms status=500 bytes=293
2015-10-20T16:59:52.252447+00:00 app[web.1]: 2015-10-20 16:59:52 - OpenSSL::SSL::SSLError - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed:
2015-10-20T16:59:52.252451+00:00 app[web.1]: 	/app/vendor/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `connect'
2015-10-20T16:59:52.252452+00:00 app[web.1]: 	/app/vendor/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
2015-10-20T16:59:52.252453+00:00 app[web.1]: 	/app/vendor/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
2015-10-20T16:59:52.252454+00:00 app[web.1]: 	/app/vendor/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `connect'
2015-10-20T16:59:52.252455+00:00 app[web.1]: 	/app/vendor/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
2015-10-20T16:59:52.252456+00:00 app[web.1]: 	/app/vendor/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'
2015-10-20T16:59:52.252456+00:00 app[web.1]: 	/app/vendor/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1375:in `request'
2015-10-20T16:59:52.252458+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/httparty-0.13.7/lib/httparty/request.rb:291:in `handle_response'
2015-10-20T16:59:52.252457+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/httparty-0.13.7/lib/httparty/request.rb:117:in `perform'
2015-10-20T16:59:52.252460+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/httparty-0.13.7/lib/httparty.rb:545:in `perform_request'
2015-10-20T16:59:52.252459+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/httparty-0.13.7/lib/httparty/request.rb:131:in `perform'
2015-10-20T16:59:52.252460+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/httparty-0.13.7/lib/httparty.rb:476:in `get'
2015-10-20T16:59:52.252461+00:00 app[web.1]: 	/app/lib/shields.rb:11:in `badge_image'
2015-10-20T16:59:52.252462+00:00 app[web.1]: 	lib/web.rb:36:in `block in <main>'
2015-10-20T16:59:52.252463+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1609:in `call'
2015-10-20T16:59:52.252464+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1609:in `block in compile!'
2015-10-20T16:59:52.252465+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
2015-10-20T16:59:52.252466+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
2015-10-20T16:59:52.252466+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
2015-10-20T16:59:52.252467+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
2015-10-20T16:59:52.252469+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
2015-10-20T16:59:52.252469+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
2015-10-20T16:59:52.252470+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
2015-10-20T16:59:52.252468+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
2015-10-20T16:59:52.252471+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
2015-10-20T16:59:52.252472+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
2015-10-20T16:59:52.252473+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
2015-10-20T16:59:52.252472+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
2015-10-20T16:59:52.252473+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
2015-10-20T16:59:52.252474+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
2015-10-20T16:59:52.252474+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
2015-10-20T16:59:52.252475+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
2015-10-20T16:59:52.252475+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
2015-10-20T16:59:52.252475+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
2015-10-20T16:59:52.252476+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
2015-10-20T16:59:52.252476+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
2015-10-20T16:59:52.252476+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
2015-10-20T16:59:52.252477+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
2015-10-20T16:59:52.252477+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
2015-10-20T16:59:52.252478+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
2015-10-20T16:59:52.252478+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
2015-10-20T16:59:52.252479+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
2015-10-20T16:59:52.252479+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
2015-10-20T16:59:52.252479+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
2015-10-20T16:59:52.252480+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
2015-10-20T16:59:52.252484+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
2015-10-20T16:59:52.252484+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
2015-10-20T16:59:52.252485+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
2015-10-20T16:59:52.252485+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
2015-10-20T16:59:52.252485+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
2015-10-20T16:59:52.252486+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
2015-10-20T16:59:52.252486+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
2015-10-20T16:59:52.252487+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
2015-10-20T16:59:52.252487+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
2015-10-20T16:59:52.252488+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:86:in `block in pre_process'
2015-10-20T16:59:52.252488+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `catch'
2015-10-20T16:59:52.252488+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `pre_process'
2015-10-20T16:59:52.252489+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:1062:in `call'
2015-10-20T16:59:52.253000+00:00 app[web.1]: 54.144.81.236 - - [20/Oct/2015:16:59:52 +0000] "GET /maven-central/org.annolab.tt4j/org.annolab.tt4j/badge.svg HTTP/1.1" 500 92 0.0926
2015-10-20T16:59:52.252489+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:1062:in `block in spawn_threadpool'
```

The reason is probably that https://search.maven.org supports only old TLS 1.0 (see [here](https://www.ssllabs.com/ssltest/analyze.html?d=search.maven.org)). :/

**Comment by jirutka** [comment]
Wait a moment… I’m not connecting to HTTPS… This is odd.

**Comment by jirutka** [comment]
I’ve upgraded to the latest [cedar stack](https://devcenter.heroku.com/articles/cedar-14-migration) on Heroku and the problem disappeared.

**Comment by cogmission** [comment]
@jirutka Thanks! good job! I love your maven badge!

**Comment by idelvall** [comment]
Thanks!  @jirutka! keep up the good work!
